### ISSUE TITLE
Cannot add Icons to the taskbar

### ISSUE THREAD

**Issue by tottelitott** [cschneegans/unattend-generator#107]
Hi...

i don't know what setting i made that prevents me from adding icons to the taskbar..

After relogon all icons are deleted again...

Any ideas?

Thanks in advance...

**Comment by cschneegans** [comment]
Well, that is not the expected behavior. There was a [similar report](https://github.com/cschneegans/unattend-generator/issues/26) a while ago, where a user saw the Start menu pins (rather than the taskbar icons) disappear.

Pleas attach your autounattend.xml file. Which image did you use to install Windows?

You may also inspect the registry key that stores the taskbar icons:

```
PS C:\> $FormatEnumerationLimit = 40; Get-Item -LiteralPath 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Taskband' | Format-Table -AutoSize

    Hive: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer

Name     Property
----     --------
Taskband FavoritesResolve : {115, 6, 0, 0, 76, 0, 0, 0, 1, 20, 2, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 70, 129, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}
         Favorites        : {0, 33, 6, 0, 0, 20, 0, 31, 128, 155, 212, 52, 66, 69, 2, 243, 77, 183, 128, 56, 147, 148, 52, 86, 225, 11, 6, 0, 0, 85, 5, 65, 80, 80, 83, 67, 5, 8, 0, 3...}
         FavoritesChanges : 2
         FavoritesVersion : 3
```

**Comment by tottelitott** [comment]
I'll look for the file. Thanks for the reply.

The icons are missing one time, next boot they appear, next boot away and so on...

I'll have a close look at this and check the registry

**Comment by cschneegans** [comment]
Also have a look at the [new settings](https://github.com/cschneegans/unattend-generator/issues/139#issuecomment-2547455403) that lets you choose between the default icons, no icons or custom icons in the taskbar.
