### ISSUE TITLE
[REQUEST] Bypass Windows 11 requirements check (MoSetup) - AllowUpgradesWithUnsupportedTPMOrCPU

### ISSUE THREAD

**Issue by denji** [cschneegans/unattend-generator#117]
```bat
:: MoSetup Bypass hardware checks during in-place upgrades (e.g., upgrading from Windows 10 to Windows 11)
reg add HKLM\SYSTEM\Setup\MoSetup /f
reg add HKLM\SYSTEM\Setup\MoSetup /v AllowUpgradesWithUnsupportedTPMOrCPU /t REG_DWORD /d 1 /f
```

```bat
:: Add Bypass Storage Check
reg add HKLM\SYSTEM\Setup\LabConfig /v BypassStorageCheck /t REG_DWORD /d 1 /f

:: Add Bypass CPU Check
:: https://github.com/ventoy/Ventoy/blob/master/vtoyjump/vtoyjump/vtoyjump.c#L2239
reg add HKLM\SYSTEM\Setup\LabConfig /v BypassCPUCheck /t REG_DWORD /d 1 /f
```

**Comment by cschneegans** [comment]
Thanks for your report! I have now added the `AllowUpgradesWithUnsupportedTPMOrCPU` registry value via https://github.com/cschneegans/unattend-generator/commit/03b9b8d28d44ac08ad0c1ac91aafeef4dcd0dd88.

I had

- `BypassStorageCheck`
- `BypassCPUCheck`
- `BypassDiskCheck`

included in the past, but removed these values via https://github.com/cschneegans/unattend-generator/commit/d079b051fc11080225bf488b15eec3882b7bdd97, leaving only

- `BypassTPMCheck`
- `BypassSecureBootCheck`
- `BypassRAMCheck`

The former ones just seem to be urban legends, without any actual effect. See the comments from [Michael Niehaus](https://oofhours.com/2022/07/25/bypassing-windows-11-hardware-requirements-revisited/) or [Paul Batard](https://github.com/pbatard/rufus/issues/1990) for reference.

If you have reliable sources indicating otherwise, please let me know.

**Comment by cschneegans** [comment]
Oh, wait a minute! I put the `AllowUpgradesWithUnsupportedTPMOrCPU` value in the _windowsPE_ phase, but now I notice you mentioned “in-place upgrades”. When setup.exe is run from within Windows (rather than Windows PE), the _windowsPE_ section in an autounattend.xml file is ignored, so setting `AllowUpgradesWithUnsupportedTPMOrCPU` in the _windowsPE_ phase does not make much sense. Does this setting rather belong in the _specialize_ phase? Sorry, I have no machine available to test this myself.

Also, what exactly is `DisableAutomaticReboot` supposed to do and in which phase does it belong? I tried to set this value during the _windowsPE_ phase as well, but Windows Setup rebooted the computer nevertheless.

**Comment by denji** [comment]
MoSetup can only affect when upgrading from Windows 10 to Windows 11 or when upgrading Windows 11 "after installation", this creates some effect when Windows 11 with newer versions stops accepting updates in some cases.
I have had crashes on client machines with Windows 11 upgrades, the upgrade cycled endlessly at the end with a crash on newer versions of Windows 11 (can't remember the specific versions now).
