### ISSUE TITLE
Diskpart

### ISSUE THREAD

**Issue by yanshkr** [cschneegans/unattend-generator#126]
Hello.

I really like your tool and it suffices everything except the ability to clean disks after copying windows files, but before the first reboot.

I'm using ventoy in conjunction with unattend.xml and would like to clean up the ventoy files after copying all the necessary windows files.

How can I best implement this?

**Comment by cschneegans** [comment]
To my knowledge, there is no hook in the unattended process that Windows Setup would call after it has finished copying files.

I would love to use such a hook myself, namely to remove 8.3 file name and to run the [DisableDefender.vbs](https://github.com/cschneegans/unattend-generator/blob/master/resource/DisableDefender.vbs) script after (rather than during) the imaging operation.

There might be some workarounds:

• Windows Setup does not reboot automatically when you have launched setup.exe with the [/NoReboot](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-command-line-options?view=windows-11#noreboot) switch, and you [can still use](https://schneegans.de/windows/no-8.3/#setup) an answer file.

• Edit certain files in the boot.wim image. In particular, by editing [Winpeshl.ini](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpeshlini-reference-launching-an-app-when-winpe-starts?view=windows-11) you can run your own commands instead of setup.exe.

**Comment by yanshkr** [comment]
Thanks for response.
