### ISSUE TITLE
[REQUEST] Remove meet now

### ISSUE THREAD

**Issue by juancesx** [cschneegans/unattend-generator#133]
Some requests (if possible)

A way to remove `meet now`, i.e:
![3gK8RcguY5](https://github.com/user-attachments/assets/ccd32b00-4dac-4e54-9882-635b470730b1)

An option to choose how the items on taskbar are combined, this can be achieved as
```ps
# -Value
# 0: Always combine, hide labels
# 1: Combine when taskbar is full
# 2: Never combine (default Windows behavior) 
Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarGlomLevel" -Value 2 -Type DWord
```

A way to pre-configure the folders, i.e:
```
right-click -> View ->      • Large items
right-click -> Group by ->  • None

```
I have found this [project](https://github.com/LesFerch/WinSetView) that looks to be able to automatize this.
I tried to check if it's possible to dump just the keys to perform a global modification but looks so complicated.

My **Win10** virtual machine (latest iso) on VMWare (with tools already instaled):

![image](https://github.com/user-attachments/assets/bfa4496b-e32c-49e3-b5fd-5c259e3b807d)

I'm trying to create the machine with a smaller disk, maybe 8GB, but i'm getting this:

![image_viewer_sELY6dCGXR](https://github.com/user-attachments/assets/51e703a7-3595-44be-830e-ae46830fe039)

Do you know a way to bypass this limitation?

**Comment by cschneegans** [comment]
> A way to remove `meet now`

Add this as a .reg file to the _Scripts to modify the default user's registry hive_ section:

```
[HKEY_USERS\DefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer]
"HideSCAMeetNow"=dword:00000001
```

AFAIK Meet Now is not a thing in Windows 11 anymore, so I don't think a dedicated setting is justified.

> A way to pre-configure the folders, i.e:

Folder customization is notoriously difficult. If there are more specialized projects, you should employ their code (which you can very well add as a custom script to your autounattend.xml file).

> I'm trying to create the machine with a smaller disk, maybe 8GB, but i'm getting this:

I don't think you can bypass the disk space requirement. Since that check is done by setup.exe, you could get around setup.exe entirely and instead apply the .wim to the target partition yourself with a call such as `dism.exe /Apply-Image`. I have no experience with this, however.
