### ISSUE TITLE
"Remove all icons" prevents pinning apps to start menu

### ISSUE THREAD

**Issue by smandon** [cschneegans/unattend-generator#142]
When enabling the "Remove all icons" option, the autounattend.xml file contains the following line (apparently to be inserted in the "C:\Windows\Setup\Scripts\Specialize.ps1" script):

`reg.exe add "HKLM\Software\Policies\Microsoft\Windows\Explorer" /v "LockedStartLayout" /t REG_DWORD /d 1 /f;`

But this registry key prevents pinning icons to the start menu, the option simply disappears from context menus. The value must be set to 0 to be able to pin apps again.

Found the info [there](https://answers.microsoft.com/en-us/windows/forum/all/windows-11-pin-to-start-menu-disappeared-from/723a476e-6dca-4465-8868-ed8002488411?page=3) after encoutering the problem on a fresh install.

Edit: Forgot to mention this was on Windows 11

**Comment by Jacosci** [comment]
See my comment here https://github.com/cschneegans/unattend-generator/issues/139#issuecomment-2555866829

It's a weird design by Microsoft because only the start menu that's getting locked down and you can still freely pin and unpin items from taskbar. And you can't customise the taskbar pins via autounattend.xml if the policy you referenced above is disabled. It really is a catch 22 circumstance.

**Comment by cschneegans** [comment]
Thanks for the report and the explanation!

This is a really ugly situation. While https://github.com/cschneegans/unattend-generator/commit/c06ff4c10347d432195b7d33cde8f6c30c4948cf addresses the problem, I am not at all happy with the side effects. 

I have basically moved the relevant registry values from `HKLM\Software\Policies\Microsoft\Windows\Explorer` to 
`HKCU\Software\Policies\Microsoft\Windows\Explorer`. Unfortunately, users have no write permissions on their own `HKCU\Software\Policies` key, so a scheduled task (running with SYSTEM privileges, of course) is needed to set the `LockedStartLayout` value to `0` once a user has logged on.

Since new users might be added to the system at any time, that task needs to run indefinitely (currently using an interval of 2 minutes). Hence, you might experience a short delay until the _Pin to Start_ menu item appears.

**Comment by cschneegans** [comment]
> Since new users might be added to the system at any time, that task needs to run indefinitely (currently using an interval of 2 minutes).

Inspired by this [blog post](https://qtechbabble.wordpress.com/2021/09/09/use-system-events-to-trigger-administrator-scheduled-tasks-from-a-standard-user-account/), I have replaced (via https://github.com/cschneegans/unattend-generator/commit/c8e47fd1615ac24859eedf58aca0e872b3f830c9) the task schedule by a event trigger, which seems like a more elegant solution.

**Comment by ProgrammerBruce** [comment]
Set-ItemProperty -LiteralPath "Registry::HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Name LockedStartLayout -Value 0;

**Comment by cschneegans** [comment]
> Set-ItemProperty -LiteralPath "Registry::HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Name LockedStartLayout -Value 0;

Using the HKLM branch simply does not work for multi-user installations.

**Comment by ProgrammerBruce** [comment]
HKLM works for me and my multi-user uses.  Not sure what you're coming up against.
