### ISSUE TITLE
Add Classic Context Menu option

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [cschneegans/unattend-generator#19]
I really hate the new one in Windows 11, do you think it's possible for you to add this...? I know it's possible through the registry editor during post-installation.

(I don't even know if you wanted people to post requests here...)

**Comment by cschneegans** [comment]
This can be achieved by adding this .reg file (found at [How-To Geek](https://www.howtogeek.com/759449/how-to-get-full-context-menus-in-windows-11s-file-explorer/)) in the _Scripts to run whenever a user logs on for the first time_ section:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}]
@=""

[HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]
@=""
```

**Comment by ShadowCodeX-debug** [comment]
Would you be willing to add an easy check option for accessibility?

**Comment by cschneegans** [comment]
Well, since I will probably need that setting myself when switching to Windows 11, I have added it via https://github.com/cschneegans/unattend-generator/commit/3b34d7366a95d9b8e75c205cdf98bb627845eee7.

In the [online form](https://schneegans.de/windows/unattend-generator/), see the new _Use classic context (right-click) menu in Windows 11_ checkbox. You might need to refresh (F5) the page.

**Comment by ShadowCodeX-debug** [comment]
Wow you're quick
