### ISSUE TITLE
[Question] Admin account vs. Built-In Administrator

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [cschneegans/unattend-generator#20]
Are the different users are the same user?

**Comment by cschneegans** [comment]
I don't quite understand the question.

A user account **Admin** would be different from the user account **Administrator**. The user account **Administrator** already exists when you install Windows, but it is inactive by default.

**Comment by ShadowCodeX-debug** [comment]
The reason I'm asking this is because there are mentions of seemingly 2 different admin accounts. In the User accounts section, there is both the "Admin" account which the name can be changed but, then theres a sub-section labeled First Logon that mentions a "Build- in Administrator" account.

I was confused on if they we're the same user or different users.

**Comment by cschneegans** [comment]
Those are indeed two different user accounts. You can create zero or more user accounts in the **Administrators** group, but you cannot use names of built-in accounts, including **Administrator**, **Guest** or **System**. The preset name **Admin** has no special significance.

The built-in account **Administrator** behaves differently than other administrator accounts. For example, it is not subject to UAC by default (see the `FilterAdministratorToken` registry value), and it also [not subject to an Account Lockout Policy](https://www.reddit.com/r/Windows10/comments/y36pr2/comment/isb5pso/) for local logins.

The form makes sure that you have at least one administrator account enabled – otherwise, you could not perform any administrative tasks on the new Windows installation.

**Comment by ShadowCodeX-debug** [comment]
Thank you.
