### ISSUE TITLE
select a disk when there are more than one disk

### ISSUE THREAD

**Issue by wellsyu** [cschneegans/unattend-generator#30]
if there are more than one disk , how could i choose the one with small volume to be the os disk ,and format it automaticlly

**Comment by wellsyu** [comment]
i find an aticle https://www.cnblogs.com/jackadam/p/18161742
but i donot know how to add the script to the xml file

**Comment by cschneegans** [comment]
You can enter a custom diskpart script, and instead of the default `SELECT DISK=0` you can select another disk by its index or location path. See [select disk](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/select-disk) and [Hard Disk Location Path Format](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/hard-disk-location-path-format) for more information.

AFAIK diskpart has no built-in facility to select the smaller of two disks.
