### ISSUE TITLE
[Bug & proposal]Bugs related to language and region

### ISSUE THREAD

**Issue by inschrift-spruch-raum** [cschneegans/unattend-generator#36]
1.The `home location` setting seems to be overridden by `Format dates, times, currency, and numbers arranging`
2.Can a second preferred language be added to the unattended file
![image](https://github.com/user-attachments/assets/1455d387-1cf6-42a8-bee6-4c37bd323362)
![image](https://github.com/user-attachments/assets/e63084b7-0be1-497b-b8b4-54151671d547)
![image](https://github.com/user-attachments/assets/fb58e2aa-be73-432c-9a5f-279764fd3d26)

**Comment by cschneegans** [comment]
To be honest, I probably never tested with Chinese images. There might be a more fundamental problem here.

I have downloaded the `Win11_23H2_Chinese_Simplified_x64v2.iso` image and created an autounattend.xml file with the settings shown in your first screenshot. Windows Setup then displays this language selection dialog:

![playground-2024-08-19-00-48-31](https://github.com/user-attachments/assets/38a38450-7ab4-4096-9518-c2338e6ba281)

This is not the expected behavior. Windows Setup should instead use the language settings from the autounattend.xml file. Did you also see this dialog? What image did you use? Also, please attach the autounattend.xml file that you have generated.

The unexpected behavior might be related to this log message written to the `X:\Windows\Panther\setupact.log` file:

> Target language [zh-Hans-CN] is NOT a valid language

![playground-2024-08-19-00-50-12](https://github.com/user-attachments/assets/1476abbf-2a33-49fe-a80a-0f88dd32ff81)

**Comment by inschrift-spruch-raum** [comment]
> This is not the expected behavior. Windows Setup should instead use the language settings from the autounattend.xml file. Did you also see this dialog? What image did you use? Also, please attach the autounattend.xml file that you have generated.
Yes, I did see this window
My unattended file:https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=zh-Hans-CN&Locale=zh-Hans-CN&Keyboard=00000409&GeoLocation=244&UseKeyboard2=true&Locale2=zh&Keyboard2=0804%3A%7B81d4e9c9-1d3b-41bc-9e6c-4b40bf79e35e%7D%7Bfa550b04-5ad7-411f-a5ac-ca038ec515d7%7D&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Custom&ComputerName=Code&TimeZoneMode=Explicit&TimeZone=China+Standard+Time&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro_workstations&UserAccountMode=Unattended&AccountName0=Zero&AccountPassword0=&AccountGroup0=Administrators&AccountName1=&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&ObscurePasswords=true&PasswordExpirationMode=Unlimited&LockoutMode=Disabled&HideFiles=HiddenSystem&ShowFileExtensions=true&DisableWidgets=true&ClassicContextMenu=true&DisableFastStartup=true&EnableLongPaths=true&EnableRemoteDesktop=true&DisableLastAccess=true&NoAutoRebootWithLoggedOnUsers=true&DisableAppSuggestions=true&PreventDeviceEncryption=true&ProcessAudit=true&ProcessAuditCommandLine=true&WifiMode=Skip&ExpressSettings=DisableAll&SystemScript0=&SystemScriptType0=Cmd&SystemScript1=&SystemScriptType1=Ps1&SystemScript2=&SystemScriptType2=Reg&SystemScript3=&SystemScriptType3=Vbs&DefaultUserScript0=&DefaultUserScriptType0=Reg&DefaultUserScript1=&DefaultUserScriptType1=Cmd&DefaultUserScript2=&DefaultUserScriptType2=Ps1&FirstLogonScript0=&FirstLogonScriptType0=Cmd&FirstLogonScript1=&FirstLogonScriptType1=Ps1&FirstLogonScript2=&FirstLogonScriptType2=Reg&FirstLogonScript3=&FirstLogonScriptType3=Vbs&UserOnceScript0=&UserOnceScriptType0=Cmd&UserOnceScript1=&UserOnceScriptType1=Ps1&UserOnceScript2=&UserOnceScriptType2=Reg&UserOnceScript3=&UserOnceScriptType3=Vbs&WdacMode=Skip--

**Comment by cschneegans** [comment]
I have noticed `Win11_23H2_Chinese_Simplified_x64v2.iso` contains a `\sources\lang.ini` file with contents

```
[Available UI Languages]
zh-cn = 3
```

and `Win11_23H2_Chinese_Traditional_x64v2.iso` contains a `\sources\lang.ini` file with contents

```
[Available UI Languages]
zh-tw = 3
```

Therefore, I have replaced the UI language code `zh-Hans-CN` with `zh-CN`, and `zh-Hant-CN` with `zh-TW` via
https://github.com/cschneegans/unattend-generator/commit/5a25a4f871f27816c263487352b3973a8be7d1c2. This works well in my tests, i.e. the manual language dialog does not longer appear. Thank you for bringing this to my attention.

Existing URLs that use the `zh-Hans-CN` or `zh-Hant-CN` codes will be redirected automatically – so just open [the form with your previous inputs](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=zh-CN&Locale=zh-Hans-CN&Keyboard=00000409&GeoLocation=244&UseKeyboard2=true&Locale2=zh&Keyboard2=0804%3A%7B81d4e9c9-1d3b-41bc-9e6c-4b40bf79e35e%7D%7Bfa550b04-5ad7-411f-a5ac-ca038ec515d7%7D&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Custom&ComputerName=Code&TimeZoneMode=Explicit&TimeZone=China%20Standard%20Time&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro_workstations&UserAccountMode=Unattended&AccountName0=Zero&AccountGroup0=Administrators&AutoLogonMode=Own&ObscurePasswords=true&PasswordExpirationMode=Unlimited&LockoutMode=Disabled&HideFiles=HiddenSystem&ShowFileExtensions=true&DisableWidgets=true&ClassicContextMenu=true&DisableFastStartup=true&EnableLongPaths=true&EnableRemoteDesktop=true&DisableLastAccess=true&NoAutoRebootWithLoggedOnUsers=true&DisableAppSuggestions=true&PreventDeviceEncryption=true&ProcessAudit=true&ProcessAuditCommandLine=true&WifiMode=Skip&ExpressSettings=DisableAll&WdacMode=Skip) and download the autounattend.xml file again.

Please run your Windows installation with the new autounattend.xml file and check if the issue is resolved.

**Comment by CodingWonders** [comment]
@cschneegans, I did a test run with your changes and it looks like it works:

![image](https://github.com/user-attachments/assets/88d107d6-2f92-48eb-b595-63e610d4a35b)

I didn't see the language selector screen

**Comment by inschrift-spruch-raum** [comment]
@cschneegans

Thank you for resolving the main issue, but there is another proposal here

> 2.Can a second preferred language be added to the unattended file

Do you have any solutions for it

**Comment by cschneegans** [comment]
I think the UI on this screen is somewhat misleading: 

![image](https://github.com/user-attachments/assets/32924830-e2df-40a9-88d0-ccd62a4ab93b)

By clicking the **Add a language** button, you don't add a preferred language to Windows, you just add a language. The preference is rather established by the order of the languages.

Hence, setting your preferred language(s) is already possible in the form:

![image](https://github.com/user-attachments/assets/9dd4b4f2-2d67-496b-a345-93811acad167)

**Comment by cschneegans** [comment]
I have realized that my own form is misleading as well. I have redesigned the form to make it clearer how the 1st, 2nd and 3rd language preference are related:

![image](https://github.com/user-attachments/assets/bf9d61f7-548b-42d6-a01e-842eb77b066c)

**Comment by inschrift-spruch-raum** [comment]
![image](https://github.com/user-attachments/assets/9a1ee097-bda4-45c6-89a6-9377d14191f8)
It seems that it still doesn't work

**Comment by cschneegans** [comment]
As I can't read Chinese characters, I had a hard time to even figure out that your screenshots shows the **Country or region** and **Regional format** settings.

You need to specify:
• What autounattend.xml settings did you use? (You can just upload your file here.)
• What was the expected result for the **Country or region** and **Regional format** settings?
• What was the actual result, i.e. what **Country or region** and **Regional format** settings are shown on your screenshot?

**Comment by inschrift-spruch-raum** [comment]
[Updated unattended file](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=zh-CN&Locale=zh-Hans-CN&Keyboard=0804%3A%7B81d4e9c9-1d3b-41bc-9e6c-4b40bf79e35e%7D%7Bfa550b04-5ad7-411f-a5ac-ca038ec515d7%7D&UseKeyboard2=true&Locale2=en-US&Keyboard2=00000409&GeoLocation=244&ProcessorArchitecture=amd64&BypassRequirementsCheck=true&BypassNetworkCheck=true&ComputerNameMode=Custom&ComputerName=Code&TimeZoneMode=Explicit&TimeZone=China+Standard+Time&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro_workstations&UserAccountMode=Unattended&AccountName0=Zero&AccountPassword0=&AccountGroup0=Administrators&AccountName1=&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&ObscurePasswords=true&PasswordExpirationMode=Unlimited&LockoutMode=Disabled&HideFiles=HiddenSystem&ShowFileExtensions=true&DisableWidgets=true&ClassicContextMenu=true&DisableFastStartup=true&EnableLongPaths=true&EnableRemoteDesktop=true&DisableLastAccess=true&NoAutoRebootWithLoggedOnUsers=true&DisableAppSuggestions=true&PreventDeviceEncryption=true&ProcessAudit=true&ProcessAuditCommandLine=true&WifiMode=Skip&ExpressSettings=DisableAll&WdacMode=Skip--)

The box above shows 'China'

**Comment by inschrift-spruch-raum** [comment]
I have currently identified the problem:
UUP image bug or NTLite encapsulation bug

**Comment by inschrift-spruch-raum** [comment]
After my testing, I discovered the reason
I removed PowerShell from NTLite
And in autounattend.xml, it is precisely using
PowerShell command Set WinHomeLocation completes region switch
But that doesn't mean I can't remove PowerShell
Because I found that such code is unnecessary
Actually, I only need to modify these four lines in autounattend.xml to achieve the purpose of setting the region
![image](https://github.com/user-attachments/assets/203684d9-424b-4034-bab6-d9776d4defb8)
![image](https://github.com/user-attachments/assets/592cc205-90cd-4cb3-a995-3ce249d39e8b)

**Comment by inschrift-spruch-raum** [comment]
So, I need you to modify the source code so that it directly sets<SystemLocale>and<UserLocale>
Instead of using PowerShell

**Comment by cschneegans** [comment]
I disagree. System locale, user locale and the home location are three distinct settings, and there is no XML element that sets the home location.

However, it appears that you can set the home location [via the registry](https://www.tenforums.com/tutorials/68106-change-country-region-home-location-windows-10-a.html#option3). Try using this .reg file in the _Scripts to run whenever a user logs on for the first time_ section:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\International\Geo]
"Nation"="244"
"Name"="US"
```

**Comment by inschrift-spruch-raum** [comment]
> I disagree. System locale, user locale and the home location are three distinct settings, and there is no XML element that sets the home location.

I think<SystemLocale>and<UserLocale>can also be optional settings for unattend-generator

**Comment by inschrift-spruch-raum** [comment]
A new idea
Create 'Oobe.xml' before OOBE startup
Using the parameter `<location>` in `Oobe. xml`
Save in `Windows\System32\Oobe\Info`
Delete files after OOBE ends
