### ISSUE TITLE
Any idea about to set EFI and WinRE partitions size keeping interacitivity to select the main partition ?

### ISSUE THREAD

**Issue by Fred-Vatin** [cschneegans/unattend-generator#4]
Hi,

Let’s say I have something like this.

![select-partition-install-clean-windows-10](https://github.com/cschneegans/unattend-generator/assets/22337329/5dc68a19-6b8a-4c49-a4e9-bf900a9ad6c0)

Then, I manually delete partitions 1, 2, 3, 4 so I end up with 2 partitions. I would want to select the first one then the setup will automatically recreate all system partitions with the given size : 
- EFI : 499 Mo
- WinRe : 1000 Mo
- Windows : the available space.

This would avoid deleting another data partition.

Any idea if it would be possible ?

**Comment by cschneegans** [comment]
You can create an autounattend.xml file with a custom diskpart script, and instead of the CLEAN command (which would wipe the entire disk) only delete the first four partitions:

```
SELECT DISK=0
SELECT PARTITION=1
DELETE PARTITION
SELECT PARTITION=2
DELETE PARTITION
SELECT PARTITION=3
DELETE PARTITION
SELECT PARTITION=4
DELETE PARTITION
CREATE PARTITION EFI SIZE=499
…
```

This [link](https://schneegans.de/windows/unattend-generator/?PartitionMode=Custom&DiskpartScript=SELECT+DISK%3D0%0D%0ASELECT+PARTITION%3D1%0D%0ADELETE+PARTITION%0D%0ASELECT+PARTITION%3D2%0D%0ADELETE+PARTITION%0D%0ASELECT+PARTITION%3D3%0D%0ADELETE+PARTITION%0D%0ASELECT+PARTITION%3D4%0D%0ADELETE+PARTITION%0D%0ACREATE+PARTITION+EFI+SIZE%3D499%0D%0AFORMAT+QUICK+FS%3DFAT32+LABEL%3D%22System%22%0D%0ACREATE+PARTITION+MSR+SIZE%3D16%0D%0ACREATE+PARTITION+PRIMARY%0D%0ASHRINK+MINIMUM%3D1000%0D%0AFORMAT+QUICK+FS%3DNTFS+LABEL%3D%22Windows%22%0D%0ACREATE+PARTITION+PRIMARY%0D%0AFORMAT+QUICK+FS%3DNTFS+LABEL%3D%22Recovery%22%0D%0ASET+ID%3D%22de94bba4-06d1-4d40-a16a-bfd50179d6ac%22%0D%0AGPT+ATTRIBUTES%3D0x8000000000000001&InstallToMode=Available) will configure the _DiskpartScript_ field accordingly.

I have not tested this setup. The data partition might inadvertently get deleted. Before you use this autounattend.xml file, backup any data you want to keep.

**Comment by Fred-Vatin** [comment]
Thanks. Since then, I thought about a USB toolkit that I could launched before installing OS to delete all system partitions and recreate them as I want. If you know one that can easily create EFI and WinRe partition with simple commands, let me know.

I could manually do it with than diskpart for WinRe creation on GPT partition but I don’t want to type that in a CLI where I can not do copy/paste : 
```
create partition primary id=de94bba4-06d1-4d40-a16a-bfd50179d6ac
gpt attributes =0x8000000000000001
```
