### ISSUE TITLE
MS Teams Removal Sometimes Doesn't Work

### ISSUE THREAD

**Issue by hellocharli** [cschneegans/unattend-generator#50]
MS appears to sometimes install Teams under the package name "MicrosoftTeams" instead of "MSTeams", causing the removal script to not remove it. Adding "MicrosoftTeams" to the package list manually appears to properly remove it.

Using the latest [Win11 23H2 Public Release Build 22631.4169](https://uupdump.net/selectlang.php?id=8dda76ff-194a-4a47-b1e7-c303136bf54e) from UUP Dump.

**Comment by cschneegans** [comment]
I have not seen the _MicrosoftTeams_ package name before, and I don't perform any tests with custom-built images. However, adding an additional package name is simple and does not do any harm. Fixed with https://github.com/cschneegans/unattend-generator/commit/7b0dea1b4afc902ad18f7b9c12fa7fb303937f6b. Thanks for the suggestion.
