### ISSUE TITLE
Add more options for further debloating

### ISSUE THREAD

**Issue by ghost** [cschneegans/unattend-generator#53]
You should add options to remove some apps that currently don't have an option to be removed in the unattend file generator.

**Comment by cschneegans** [comment]
Game Bar will be uninstalled when you select **Xbox Apps**.

There have been several requests to remove Edge in the past. I am aware that scripts to remove Edge do exist, but these seem ridiculously complicated to me. Instead, I have added an option to make Edge uninstallable. This works by modifying the `C:\Windows\System32\IntegratedServicesRegionPolicySet.json` so that the **Edge is uninstallable** policy will be enabled for all devices, while it is by default only enabled for devices located in the European Economic Area. If your Windows installation has this file (which is the case at least for `Win11_23H2_English_x64v2.iso`), you will then be able to uninstall Edge via the Settings app:

![image](https://github.com/user-attachments/assets/69494f9b-378e-4c26-9ca5-fed12e7c26ca)

I also tried to run the `"C:\Program Files (x86)\Microsoft\Edge\Application\…\Installer\setup.exe" --uninstall --msedge --channel=stable --system-level --verbose-logging` command automatically, but this fails for two reasons:

- `setup.exe` will only proceed if its parent process is `sihost.exe`. It quits if its parent process is `powershell.exe`.
- There is a confirmation dialog, and setup.exe apparently does not support switches such as `--silent`, `--quiet` or `--force`:

![image](https://github.com/user-attachments/assets/f0bd51ea-9ce4-4fed-8c99-181550112d7b)

**Comment by cschneegans** [comment]
Which Windows image did you use? For example, with the **Windows11_InsiderPreview_Client_x64_en-us_26100.1150.iso** image  the **Uninstall** button is clickable, but doesn't do anything when clicked. I assume this is due to the preview state of that image.

**Comment by cschneegans** [comment]
I have installed Windows from the Win11_23H2_English_x64v2.iso image using an autounattend.xml file with the **Make Edge uninstallable** option selected. These are my findings:

• Before I run Windows Update, Edge is uninstallable. Edge remains uninstalled even after Windows Update runs.

• As you have noted, Windows Update – probably because of the Cumulative Update KB5043076 – will reset the **IntegratedServicesRegionPolicySet.json** file to its original state. After this, Edge can no longer be uninstalled. The **Uninstall** button is still clickable, but clicking it does not uninstall Edge. The log file `C:\Windows\SystemTemp\msedge_installer.log` confirms this with these messages:

```
[…VERBOSE1:install_util.cc(284)] Existing version found: 129.0.2792.52
[…VERBOSE1:shell_util.cc(4074)] Stable: didn't check uninstall policy, or policy disabled
[…WARNING:setup_main.cc(3440)] Uninstall was blocked for this product: 93
```

As far as I can see, this is simply a timing issue: if you want to uninstall Edge, do it before you run Windows Update.
