### ISSUE TITLE
Something in autounattend.xml prevents "Select setup option" screen (Previous Setup Version)

### ISSUE THREAD

**Issue by eugenesan** [cschneegans/unattend-generator#67]
I've being experimenting with 24H2 and found that even with default autounattend.xml, `Select setup option` screen won't appear and therefor `Previous Setup Version` is not available.

It took sometime to figure since the new setup was silently picking up autounattend.xml from unexpected location.
For example, now you can place the autounattend.xml on the ventoy drive root (with no plugins or configuration).

I tried a few configs and even with the default one, the screen is missing.

We need to figure out which option needs to be disabled to allow legacy installer to follow 8.3 names instructions and be able to install on Ventoy.

**Comment by cschneegans** [comment]
Windows Setup will automatically search for autounattend.xml files at various locations. This is [well-documented](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-automation-overview?view=windows-11#implicit-answer-file-search-order) and AFAIK has not changed between 24H2 and earlier versions of Windows.

I have no experience with Ventoy. Does Ventoy launch setup.exe with an `/Unattend` switch? It seems that the new ConX setup.exe does not support any command line switches.

If you want to use **both** an answer file **and** legacy setup mode with 24H2, I recommended the following steps:

1. Check the **Use filename notautounattend.xml rather than autounattend.xml** setting in my generator. (Without this setting, the autounattend.xml file would immediately be processed by ConX setup, and you would have no chance to switch to legacy setup mode.)
2. When the ConX setup starts, click **Next** twice, then click **Previous Version of Setup**:
![image](https://github.com/user-attachments/assets/b96c1d16-4332-4c93-8cf4-cf50850f5432)
3. When legacy setup has launched, press Shift+F10 to open a command prompt, then type `setup.exe /NoReboot /Unattend:D:\notautounattend.xml` to continue with an answer file. (You may need to replace `D:\` with another drive.)

I have not found a way to automate this. I am aware of [a post by user garlin](https://www.elevenforum.com/t/w11-24h2-and-old-installation-setup.25706/post-476942) who suggests to add

```
<RunSynchronousCommand wcm:action="add">
	<Description>Switch to legacy Setup</Description>
	<Order>1</Order>
	<Path>reg add "HKEY_LOCAL_MACHINE\SYSTEM\Setup" /v CmdLine /t REG_SZ /d "X:\sources\setup.exe" /f</Path>
</RunSynchronousCommand>
```

to the `windowsPE` pass. I could not make this work, and I don't even see how this is supposed to work: Adding a registry value that tells Windows Setup how to lauch setup.exe seems pointless when an instance of setup.exe already runs.

**Comment by eugenesan** [comment]
Thank you for providing such an extensive explanation!
It cleared quite a few things for me.

I am not sure how Ventoy mounts ISOs and manages the autounattend.xml file, but it seems like they are assuming that setup won't look for the answers file anywhere except specified location.
To "inject" answers file they use a plugin (https://www.ventoy.net/en/plugin_autoinstall.html).
What made this whole situation very confusing is that with 24H2 I was assuming the file is being "injected" by the plugin and not accessible by the setup without the plugin. What probably was happening is that Ventoy was failing to inject the answers file due to the new setup and the new setup finding the file by itself on the media root.
It's worth mentioning that with 23H2, disabling the plugin was enough to disable the answers file even if it was located at the media root. At least I think so, it's hard to be sure after all the experiments...

I any case, now with your help we have a way of using the answers file with the legacy setup, which unfortunately is required by Ventoy.

TBH, I feel a bit silly by not putting 2+2 yesterday while reading your [instructions](https://schneegans.de/windows/no-8.3/#setup) ;-)

Regarding automating the start of the legacy setup, while it's not a priority, I think there is hope.
If you look closely, just before the new setup starts (with or without the answers file) the screen blinks 2-3 times as if terminal commands are being executed. I have a feeling that a check is being performed to determine which setup to run. 

I believe the issue can be closed.
