### ISSUE TITLE
Activating Eea option outside europe

### ISSUE THREAD

**Issue by procionecurioso** [cschneegans/unattend-generator#7]
I don't know if it's possible but I saw that the possibility to change the home location was added, I wanted to know if in general there was a possibility to somehow activate the options that are there when you install windows with a europe iso (uninstall edge or disable bing search) with an american iso, because it seems that if you change the ids to make it look like for example you are in Germany it makes you uninstall edge, I don't know if in general it's feasible with an unattend file but I wanted to ask

**Comment by cschneegans** [comment]
To be honest, I am somewhat out of the loop regarding this European Economic Area/Digital Markets Act topic. 

Microsoft's [press release](https://blogs.microsoft.com/eupolicy/2024/03/07/microsoft-dma-compliance-windows-linkedin/) and this [blog post](https://blogs.windows.com/windows-insider/2023/11/16/previewing-changes-in-windows-to-comply-with-the-digital-markets-act-in-the-european-economic-area/) seem to imply delivery via Windows Update (rather than new ISOs that incorporate the DMA changes). Without new ISOs, an unattended installation would not be able to uninstall Edge.
