### ISSUE TITLE
Remove bloatware didnt work after update

### ISSUE THREAD

**Issue by SatL1Ng** [cschneegans/unattend-generator#8]
Used your generator a week ago. And the file structure was different. On the old version, Remove bloatware cleaned the system perfectly. Now I created a new file and some things are still there, like powershell ise. Also, when installing with a new file, some windows are completed with errors, but what exactly I do not have time to capture

**Comment by cschneegans** [comment]
I did some refactoring, and this might very well be a regression bug. Please attach the autounattend.xml file here. What OS version and edition did you use?

Also check these log files which might indicate the cause of this problem:

- `C:\Windows\Temp\remove-caps.log`
- `C:\Windows\Temp\remove-features.log`
- `C:\Windows\Temp\remove-packages.log`

**Comment by SatL1Ng** [comment]
C:\Windows\Temp\ - empty
version windows 24H2 pro en-us
[autounattend.zip](https://github.com/cschneegans/unattend-generator/files/15160704/autounattend.zip)
I am attaching the old file and an example of the new one. The old one works fine.

**Comment by cschneegans** [comment]
I hadn't tried 24H2 before, but have now downloaded an image file _Windows11_InsiderPreview_Client_x64_en-us_26080.iso_, which indeed could not process my autounattend.xml files.

It appears that Windows 24H2 stumbles over the UTF-8 byte order mark that `System.Xml.XmlWriter` emits by default. Fixed with https://github.com/cschneegans/unattend-generator/commit/aca6de788c4ba328f2013990d3519c8721e9509a. Thank you for bringing this to my attention!

**Comment by SatL1Ng** [comment]
Did a quick check. At first glance, it seems to be working. Thank you for your site generator.

**Comment by SatL1Ng** [comment]
Did a quick check. At first glance, it seems to be working. Thank you for your site generator.
