### ISSUE TITLE
[REQUEST] Don't show hidden files, but DO show protected operating system files

### ISSUE THREAD

**Issue by InterClaw** [cschneegans/unattend-generator#91]
Would it be possible to have an option to show protected operating system files, but still don't show hidden files? I don't think any of the current options allow that. I think that's the only combination not possible.

If possible, perhaps these options would be better as two tickboxes instead of the three radio buttons now?
- Show hidden files
- Show protected operating system files

![image](https://github.com/user-attachments/assets/52da7ef2-6c1e-4ccf-86b3-5dea9f2089ce)

**Comment by InterClaw** [comment]
As a workaround I can always run this on first user logon:

reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" /v ShowSuperHidden /t REG_DWORD /d 1 /f

**Comment by cschneegans** [comment]
In Folder Options, **Hidden files and folders** can be set to either **Don't show hidden files…** or to **Show hidden files…**, and **Hide protected operating system files** can either be checked or unchecked. This creates four possible combinations.

However, if **Hidden files and folders** is set to **Don't show hidden files…**, the state of **Hide protected operating system files** does not matter. This is because File Explorer considers a file a “protected operating system file” if and only if it has both the `Hidden` and the `System` attribute.

So in practice, there are only three reasonable combinations, which are represented by the three radio buttons in the form.

**Comment by InterClaw** [comment]
Well I have it unticked, so that I get all files when I show hidden files. Otherwise I have to change two settings every time to get to them.

Anyway, I have my workaround as part of the regentries I change if you don't want to change it. :)

```
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]
"ShowSuperHidden"=dword:00000001
```
